source 'https://cdn.cocoapods.org/'
platform :ios, '15.6'

target 'lynxdex' do

  pod 'Lynx', '3.2.0-rc.0', :subspecs => [
    'Framework',
  ]

  pod 'PrimJS', '2.11.1-rc.0', :subspecs => ['quickjs', 'napi']

   # integrate image-service, log-service, and http-service
   pod 'LynxService', '3.2.0-rc.0', :subspecs => [
    'Image',
    'Log',
    'Http',
]

# ImageService dependencies:
pod 'SDWebImage','5.15.5'
pod 'SDWebImageWebPCoder', '0.11.0'
end
